In [4]:
import os, sys

import pandas as pd
import numpy as np
parts=os.getcwd().split('/')
print(parts)
if (parts[-1]=='scripts') |(parts[-1]=='notebooks'):
    parts=parts[:-1]
srcpath='/'.join(parts)+'/results/'
dname='diabetes'
exp_type='random'
respath='%s/%s_%s_unlearning.csv'%(srcpath, dname, exp_type)
res_df=pd.read_csv(respath, sep='\t')
colnames=list(res_df.columns)
print(np.sort(colnames))

['', 'mnt', 'nvme1n1p2', 'codes_datasets', 'toolboxes', 'unlearn-lvq', 'notebooks']
['et_retrain' 'et_unlearn' 'iter' 'n_retrain' 'n_test'
 'num_unlearned_samples' 'prot_dev_01' 'prot_dev_02' 'prot_dev_12'
 'prot_per_class' 'solver_type' 'te_M0_AUC' 'te_M0_Bacc' 'te_M0_nAcc'
 'te_M1_AUC' 'te_M1_Bacc' 'te_M1_nAcc' 'te_M2_AUC' 'te_M2_Bacc'
 'te_M2_nAcc' 'te_imp_corr_M1' 'te_imp_corr_M2' 'te_lost_preds_M1'
 'te_lost_preds_M2' 'te_retain_corr_M1' 'te_retain_corr_M2' 'tr_M0_AUC'
 'tr_M0_Bacc' 'tr_M0_nAcc' 'tr_M1_AUC' 'tr_M1_Bacc' 'tr_M1_nAcc'
 'tr_M2_AUC' 'tr_M2_Bacc' 'tr_M2_nAcc' 'tr_imp_corr_M1' 'tr_imp_corr_M2'
 'tr_lost_preds_M1' 'tr_lost_preds_M2' 'tr_retain_corr_M1'
 'tr_retain_corr_M2']

In [11]:
temp_df['%s_retain_corr_%s'%(subset, model)]

    tr_retain_corr_M1  tr_retain_corr_M1
0               47000              47000
1               47003              47003
2               46997              46997
3               46956              46956
4               46931              46931
5               46956              46956
6               46521              46521
7               46543              46543
8               46505              46505
9               44576              44576
10              44586              44586
11              44589              44589
12              42454              42454
13              42495              42495
14              42326              42326
15              38437              38437
16              38335              38335
17              38286              38286

In [6]:
ppc=1
sel_col=['solver_type', 'prot_per_class', 'num_unlearned_samples', 'iter','n_retrain', 'tr_M0_nAcc',
        'tr_M1_nAcc', 'tr_retain_corr_M1','tr_lost_preds_M1', 'tr_imp_corr_M1',
        'tr_M2_nAcc', 'tr_retain_corr_M2','tr_lost_preds_M2', 'tr_imp_corr_M2', 
        'te_M0_nAcc',
        'te_M1_nAcc', 'te_retain_corr_M1','te_lost_preds_M1', 'te_imp_corr_M1',
        'te_M2_nAcc', 'te_retain_corr_M2','te_lost_preds_M2', 'te_imp_corr_M2']
temp_df=res_df[sel_col].loc[(res_df['solver_type']=='lbfgs') &(res_df['prot_per_class']==ppc)]
models, subsets=['M1', 'M2'], ['tr', 'te']
for model in models:
    for subset in subsets:
        res_df['%s_Acc_%s'%(subset, model)]=temp_df['%s_%s_nAcc'%(subset, model)]/temp_df['n_retrain']
#temp_df['%s_Acc_%s'%(subset, model)]=temp['%s_%s_nAcc'%(subset, model)]/temp['n_retrain']
#temp_df['%s_Acc_%s'%(subset, model2)]=temp['%s_%s_nAcc'%(subset, model2)]/temp['n_retrain']
        temp_df['%s_retrain_frac_%s'%(subset, model)]=temp_df['%s_retain_corr_%s'%(subset, model)]/temp_df['n_retrain']
        temp_df['%s_loss_frac_%s'%(subset, model)]=temp_df['%s_lost_preds_%s'%(subset, model)]/temp_df['n_retrain']
        temp_df['%s_gain_frac_%s'%(subset, model)]=temp_df['%s_imp_corr_%s'%(subset, model)]/temp_df['n_retrain']

prf_metrics=list(np.setdiff1d(list(temp_df.columns), colnames))
prf_metrics

['te_gain_frac_M1',
 'te_gain_frac_M2',
 'te_loss_frac_M1',
 'te_loss_frac_M2',
 'te_retrain_frac_M1',
 'te_retrain_frac_M2',
 'tr_gain_frac_M1',
 'tr_gain_frac_M2',
 'tr_loss_frac_M1',
 'tr_loss_frac_M2',
 'tr_retrain_frac_M1',
 'tr_retrain_frac_M2']

In [7]:
temp_df[prf_metrics]

,te_gain_frac_M1,te_gain_frac_M2,te_loss_frac_M1,te_loss_frac_M2,te_retrain_frac_M1,te_retrain_frac_M2,tr_gain_frac_M1,tr_gain_frac_M2,tr_loss_frac_M1,tr_loss_frac_M2,tr_retrain_frac_M1,tr_retrain_frac_M2
0,0.000025,0.007813,0.000025,0.004349,0.144688,0.140363,0.000012,0.032296,0.000086,0.017346,0.577374,0.560114
1,0.000000,0.006695,0.000000,0.003673,0.144712,0.141039,0.000098,0.027947,0.000025,0.014643,0.577411,0.562793
2,0.000025,0.049249,0.000012,0.054077,0.144700,0.090635,0.000000,0.200889,0.000135,0.213960,0.577337,0.363512
3,0.000012,0.025378,0.000000,0.018701,0.144840,0.126139,0.000123,0.104634,0.000086,0.076256,0.577344,0.501174
4,0.000086,0.029731,0.000098,0.021480,0.144744,0.123362,0.000234,0.121247,0.000529,0.086598,0.577044,0.490975
5,0.000012,0.004168,0.000025,0.003086,0.144817,0.141756,0.000061,0.017644,0.000160,0.012480,0.577352,0.565031
6,0.000099,0.031673,0.000062,0.022678,0.146081,0.123465,0.000211,0.128080,0.000273,0.089745,0.577141,0.487668
7,0.000062,0.027010,0.000037,0.018300,0.146115,0.127852,0.000161,0.108721,0.000174,0.072915,0.577449,0.504708
8,0.000074,0.032381,0.000099,0.023349,0.146051,0.122801,0.000199,0.130989,0.000484,0.093546,0.576971,0.483909
9,0.000297,0.027176,0.000736,0.018354,0.151421,0.133803,0.001395,0.104392,0.002545,0.069375,0.575769,0.508938
10,0.000207,0.032581,0.000400,0.023128,0.151723,0.128995,0.000852,0.125392,0.001627,0.088356,0.575771,0.489043
11,0.000478,0.027399,0.000349,0.018257,0.151751,0.133843,0.002479,0.105076,0.001304,0.069336,0.575721,0.507689
12,0.000231,0.029867,0.000258,0.020378,0.159668,0.139548,0.000896,0.109790,0.001045,0.074533,0.576359,0.502871
13,0.000366,0.028923,0.000258,0.019517,0.159627,0.140368,0.001439,0.105635,0.000706,0.071066,0.576766,0.506406
14,0.000896,0.026793,0.000557,0.017925,0.159413,0.142044,0.003653,0.098290,0.001806,0.063635,0.574777,0.512948
15,0.000210,0.022016,0.000300,0.014037,0.176367,0.162630,0.000795,0.073126,0.000975,0.045307,0.576448,0.532117
16,0.000735,0.024814,0.000510,0.016413,0.176221,0.160318,0.003016,0.082544,0.001335,0.051939,0.575126,0.524522
17,0.000960,0.025259,0.000525,0.016724,0.176169,0.159969,0.003720,0.084027,0.001635,0.053338,0.574270,0.522567